### ISSUE TITLE
cant get from global id ->  is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

### ISSUE THREAD

**Issue by alibaltschun** [graphql-python/graphene-mongo#136]
hello, i do a query and return the id, after that i do mutation with that id.
but that id not match for objects.get(id=id)
this is my query

```
 {
   userLogin(email:"test2@gmail.com",password:"test123"){   
     id
   }
}
```
and return

```
 {
   "data": {
     "userLogin": {
       "id": "VXNlcjo1ZTVlMWRkYWVkMGQ2ZmU1MWNhZmRhMmE="
     }
   }
 }
```

but i cant do mutation with that id

 ```
mutation{
   userUpdate(input:{
     userData:{
         name:"test_create_user_edit5"
     }
     clientMutationId:"VXNlcjo1ZTVlMWRkYWVkMGQ2ZmU1MWNhZmRhMmE="
   }){
     user{
       name
       id
     }
   }
 }
```

and return

 ```
{
   "errors": [
     {
       "message": "'VXNlcjo1ZTVlMWRkYWVkMGQ2ZmU1MWNhZmRhMmE=' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string",
       "locations": [
         {
           "line": 2,
           "column": 3
         }
       ],
       "path": [
         "userUpdate"
       ]
     }
   ],
   "data": {
     "userUpdate": null
   }
 }

```
mongoengine : '0.19.1'
graphene-mongo : 

thanks

**Comment by abawchen** [comment]
@alibaltschun : Would you please provide your implementation of mutation? say `UserUpdate`, thanks.

**Comment by alibaltschun** [comment]
i do not solve this problem with this technique, but i already change my code with jwt, and search base on jwt. and its work.

**Comment by floydspace** [comment]
I would like it to be reopened because the issue still occurs.
The issue here is that when you try to save global id as a foreign key, it fails with `is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string`, because it expects to see mongo ObjectId hex string
Can the objectId be somehow recognized automatically? or can we somehow use ObjectId hex as a global identifier instead?
Thank you
