### ISSUE TITLE
MongoEngineConversionError: Don't know how to convert the MongoEngine field <class 'mongoengine.fields.StringField'> (<class 'type'>)

### ISSUE THREAD

**Issue by Ahmedn1** [graphql-python/graphene-mongo#151]
When I have a list field like this:  
`some_field = graphene.List(graphene.String)`  
Then I build a `MongoEngineObjectType` for it:  
```
class new_ObjectType(MongoengineObjectType):
    class Meta:
        model = BaseObjectType
```  
  
I get this error because this method `convert_field_to_list` calls this method `convert_mongoengine_field` which always raises the exception.

**Comment by miguescri** [comment]
I encountered a problem that resulted in the `MongoEngineConversionError` and when googling this was the only issue/post I found, so I'll add some clarifications for future reference.

The `graphene_mongo.converter.convert_mongoengine_field` function is generic; it is decorated with [`functools.singledispatch`](https://docs.python.org/3/library/functools.html#functools.singledispatch) and all the other functions in `graphene_mongo.converter` are implementations of `convert_mongo_engine_field` for different `mongoengine` field types. The only way to raise the `MongoEngineConversionError` exception inside `convert_mongo_engine_field` is by providing an argument that is not recognized by any of the supported `mongoengine` fields.

The `convert_field_to_list` implementation recursively calls `convert_mongoengine_field` to convert the type of items that the list holds, which may be any kind of `mongoengine` fields (lists included). Again, this will only raise the exception if the type of the list's contents is not supported.

Regarding the original question, the `Meta.model` attribute in a `MongoengineObjectType` needs to inherit from `mongoengine.Document`. If you are providing `graphene` field types inside a `mongoengine.Document` or providing `Meta.model` with a `graphene.ObjectType`, it will break because won't be able to do the conversion.

**Comment by abawchen** [comment]
@miguescri : Thanks for your explanation
@Ahmedn1 : Does it answer your question? i.e `the Meta.model attribute in a MongoengineObjectType needs to inherit from mongoengine.Document`

**Comment by leonardwellthy** [comment]
I managed to reproduce this problem with the exact same error message, but a different root cause. So for future Googlers, here's my example:
```
from graphene_mongo import MongoengineObjectType
from mongoengine import Document, ListField, StringField


class ExampleDocumentModel(Document):
    example_list_field = ListField(StringField)


class ExampleType(MongoengineObjectType):
    class Meta:
        model = ExampleDocumentModel
```

and the problem is that [a Mongoengine ListField takes another field _**object**_ as its parameter](https://docs.mongoengine.org/guide/defining-documents.html#list-fields), not a field **_class_**. Which is exactly what the error message is saying, I just couldn't interpret it without lots of trial and error.

So the corrected Mongoengine model should look like:
```
class ExampleDocumentModel(Document):
    example_list_field = ListField(StringField())
```
